# fly.toml app configuration file generated for medscan-notificacao-0mzgog on 2025-03-04T22:50:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medscan-notificacao-0mzgog'
primary_region = 'gig'

[build]

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
